### ISSUE TITLE
Improve the error message when push isn't configured on DUO

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/awslogin#7]
The current error message is:
```awslogin
BYU Net ID: johnrb2
Password: 

Sending request for authentication
Traceback (most recent call last):
  File "/usr/local/bin/awslogin", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/byu_awslogin/index.py", line 88, in main
    fire.Fire(cli)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 120, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 358, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 561, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/byu_awslogin/index.py", line 42, in cli
    html_response, session, auth_signature, duo_request_signature = authenticate(username, password)
  File "/usr/local/lib/python3.6/site-packages/byu_awslogin/adfs_auth.py", line 40, in authenticate
    auth_signature, duo_request_signature = _authenticate_duo(login_response_html_soup, True, session)
  File "/usr/local/lib/python3.6/site-packages/byu_awslogin/adfs_auth.py", line 103, in _authenticate_duo
    session
  File "/usr/local/lib/python3.6/site-packages/byu_awslogin/adfs_auth.py", line 303, in _begin_authentication_transaction
    u'Cannot begin authentication process. The error response: {}'.format(response.text)
RuntimeError: Cannot begin authentication process. The error response: {"message": "Unknown authentication method.", "stat": "FAIL"}
```

The message should be much more clear about what the problem is and how to fix it.

**Comment by evade-ninja** [comment]
Is this a better error message? Do we need to tell the user how to enable auto-push?

```
Sending request for authentication
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    fire.Fire(index.cli)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fire/core.py", line 120, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fire/core.py", line 358, in _Fire
    component, remaining_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fire/core.py", line 561, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/Users/travis/dev/awslogin/byu_awslogin/index.py", line 42, in cli
    html_response, session, auth_signature, duo_request_signature = authenticate(username, password)
  File "/Users/travis/dev/awslogin/byu_awslogin/adfs_auth.py", line 40, in authenticate
    auth_signature, duo_request_signature = _authenticate_duo(login_response_html_soup, True, session)
  File "/Users/travis/dev/awslogin/byu_awslogin/adfs_auth.py", line 103, in _authenticate_duo
    session
  File "/Users/travis/dev/awslogin/byu_awslogin/adfs_auth.py", line 304, in _begin_authentication_transaction
    u'Generic Authentication Failure.\nAre you enrolled in Duo MFA?\nDid you enable Duo automatic push?'
RuntimeError: Generic Authentication Failure.
Are you enrolled in Duo MFA?
Did you enable Duo automatic push?
```

**Comment by pauldeden** [comment]
I would not show the traceback and just show the error message.  It's cleaner.

**Comment by evade-ninja** [comment]
I've got it down to:
```
Sending request for authentication
Generic Authenticaion Failure.
Are you enrolled in Duo MFA?
Did you enable Duo automatic push?
```

**Comment by pauldeden** [comment]
Looks great!

**Comment by pauldeden** [comment]
We just need to increment the version number in VERSION and push that change and we can close this issue.

**Comment by evade-ninja** [comment]
Incremented the version number and pushed the change.
